### ISSUE TITLE
support jwts signed using EdDSA algorithm

### ISSUE THREAD

**Issue by wildsylvan** [powersync-ja/powersync-service#72]
> EdDSA is known as a high performance signature algorithm with small key sizes and signatures. Using EdDSA signatures over RSA saves time, money and resources. EdDSA is also more secure than RSA.
> EdDSA is deterministic and does not depend on a random number generator for security. The requirement of a nonce and random number generator to create one has lead to known vulnerabilities in ECDSA implementations in the past. In addition, EdDSA does not require expensive point validation for corner cases. Consequently, EdDSA is more secure than ECDSA because it is simply easier to implement.
> As long as there are no other requirements that dictate the use of certain signature algorithms, switch to EdDSA if you can. It's fast, it's secure, and it's green.

https://github.com/powersync-ja/powersync-service/blob/a9ec391f2a66c987b084317a7cfa626334d882f3/packages/service-core/src/auth/KeySpec.ts#L5

**Comment by LucDeCaf** [comment]
Hi @wildsylvan, [this PR](https://github.com/powersync-ja/powersync-service/pull/142) just got merged, which should allow you to use EdDSA in hopefully the next version of the service 👍

**Comment by rkistner** [comment]
This is now available in the latest self-hosted and cloud versions. Thanks @LucDeCaf!
